name: golangci-lint Checks

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - .github/workflows/golangci-lint.yml
      - .ci/.golangci*.yml
      - .ci/tools/**
      - internal/**
      - go.sum
      - main.go
      - names/**
      - tools/**

jobs:
  golangci-linta:
    name: 1 of 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
      - id: golangci-lint-version
        working-directory: .ci/tools
        run: >-
          echo "version=$(
            go list -m all |
            grep github.com/golangci/golangci-lint |
            awk '{print $2}'
          )" >> $GITHUB_OUTPUT
      - name: golangci-lint
        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3.6.0
        with:
          version: "${{ steps.golangci-lint-version.outputs.version }}"
          args: --config .ci/.golangci.yml
  golangci-lintb:
    name: 2 of 2
    needs: [golangci-linta]
    runs-on: [custom, linux, xl]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
      - id: golangci-lint-version
        working-directory: .ci/tools
        run: >-
          echo "version=$(
            go list -m all |
            grep github.com/golangci/golangci-lint |
            awk '{print $2}'
          )" >> $GITHUB_OUTPUT
      - name: golangci-lint
        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3.6.0
        with:
          version: "${{ steps.golangci-lint-version.outputs.version }}"
          args: --config .ci/.golangci2.yml
        env:
          # Trigger garbage collection more frequently to reduce the likelihood
          # of OOM errors.
          # ref: https://golangci-lint.run/usage/performance/#memory-usage
          GOGC: "50"
